### ISSUE TITLE
Support for authentication keys

### ISSUE THREAD

**Issue by jjczopek** [simonkurtz-MSFT/python-openai-loadbalancer#32]
Examples in the code/tests leverage using the managed identity authorization with via `token_provider`.
If the current solution supports connecting to endpoints with API keys, ti would be good to update documentation.

If the solution does not support connecting to endpoints via API keys at the moment, this is a feature request :)

**Comment by simonkurtz-MSFT** [comment]
Hi @jjczopek, thinking through this a bit, we would need to keep track of different keys for different backends. Using an identity is the safer approach, but I could extend it for keys.
